#!/bin/sh

# Install base Android SDK and components
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install -qq libstdc++6:i386 lib32z1
sudo apt-get install openjdk-7-jdk
sudo apt-get install curl

export COMPONENTS=build-tools-19.0.2,android-19,sysimg-19,extra-android-support,extra-google-google_play_services,extra-google-gcm,extra-google-m2repository,extra-android-m2repository

curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-1/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
